version: '3.8'
services:
  api:
    build:
      context: .
      dockerfile: docker/dev/django/Dockerfile
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    command: /start
    env_file:
      - .envs/.dev/.django
    restart: always
    networks:
      - backend_network

networks:
  backend_network:
    driver: bridge