# Generated by Django 4.2.11 on 2024-11-04 03:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_on', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_on', models.CharField(blank=True, max_length=100, null=True)),
                ('deleted_on', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(upload_to='attachments')),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Invoice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_on', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_on', models.CharField(blank=True, max_length=100, null=True)),
                ('deleted_on', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='invoice/')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_rejected', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
                ('date_paid', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_on', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_on', models.CharField(blank=True, max_length=100, null=True)),
                ('deleted_on', models.CharField(blank=True, max_length=100, null=True)),
                ('skill', models.CharField(blank=True, max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_on', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_on', models.CharField(blank=True, max_length=100, null=True)),
                ('deleted_on', models.CharField(blank=True, max_length=100, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('from_date', models.CharField(blank=True, max_length=100, null=True)),
                ('to_date', models.CharField(blank=True, max_length=100, null=True)),
                ('time_logged', models.CharField(blank=True, max_length=100, null=True)),
                ('amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('revision', models.IntegerField(blank=True, default=0, null=True)),
                ('is_invoiced', models.BooleanField(default=False)),
                ('is_paid', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='SubtaskFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_on', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_on', models.CharField(blank=True, max_length=100, null=True)),
                ('deleted_on', models.CharField(blank=True, max_length=100, null=True)),
                ('file', models.FileField(blank=True, null=True, upload_to='subtask_files/')),
                ('name', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Task',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True)),
                ('is_delete', models.BooleanField(default=False)),
                ('created_on', models.CharField(blank=True, max_length=100, null=True)),
                ('updated_on', models.CharField(blank=True, max_length=100, null=True)),
                ('deleted_on', models.CharField(blank=True, max_length=100, null=True)),
                ('title', models.CharField(blank=True, max_length=100)),
                ('description', models.TextField(blank=True)),
                ('budget', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('total_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('remaining_amount', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('currency', models.CharField(blank=True, max_length=100)),
                ('bid_type', models.CharField(blank=True, choices=[('open', 'Open'), ('closed', 'Closed'), ('max_price', 'Max Price')], max_length=100)),
                ('bid_deadline', models.CharField(blank=True, max_length=100, null=True)),
                ('job_type', models.CharField(blank=True, choices=[('remote', 'Remote'), ('hybrid', 'Hybrid'), ('onsite', 'Onsite')], max_length=100)),
                ('experience_level', models.CharField(blank=True, choices=[('entry', 'Entry'), ('intermediate', 'Intermediate'), ('expert', 'Expert')], max_length=100)),
                ('task_deadline', models.CharField(blank=True, max_length=100, null=True)),
                ('acceptance_criteria', models.TextField(blank=True)),
                ('is_completed', models.BooleanField(default=False)),
                ('is_accepted', models.BooleanField(default=False)),
                ('is_worker_accepted', models.BooleanField(default=False)),
                ('is_fully_paid', models.BooleanField(default=False)),
                ('progress', models.IntegerField(blank=True, null=True)),
                ('status', models.CharField(blank=True, choices=[('in_progress', 'In Progress'), ('pending', 'Pending'), ('completed', 'Completed')], max_length=100)),
                ('is_sub_contractors_only', models.BooleanField(default=False)),
                ('exit_criteria', models.TextField(blank=True)),
                ('communication_deadline', models.CharField(blank=True, max_length=100, null=True)),
                ('communication_type', models.CharField(blank=True, choices=[('open', 'open'), ('closed', 'closed'), ('no', 'no')], max_length=100)),
                ('is_origin_organization', models.BooleanField(default=False)),
                ('is_post_approved', models.BooleanField(default=False)),
                ('is_post_rejected', models.BooleanField(default=False)),
                ('post_approved_on', models.CharField(blank=True, max_length=100, null=True)),
                ('is_worker_organization', models.BooleanField(default=False)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
